name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
       xcodebuild test -project OpenMarket/OpenMarket.xcodeproj -scheme OpenMarket -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=14.2'
