name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
       xcodebuild clean test -project OpenMarket.xcodeproj -scheme OpenMarket -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.0'
